# Generated by Django 3.1.7 on 2021-02-21 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('pipeline_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('usermodel_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('project_status', models.CharField(max_length=250)),
                ('woi', models.BooleanField(default=list, null=True)),
                ('ProjProfileFilter', models.BooleanField(default=list, null=True)),
                ('allprojectcustomfieldsOOI', jsonfield.fields.JSONField()),
                ('dateprojcounter', models.IntegerField(default=0)),
                ('hitlist', models.BooleanField(default=list, null=True)),
                ('projintakes', models.BooleanField(default=list, null=True)),
                ('startDays', models.IntegerField(default=0)),
                ('billabledmtproject0001setupclienttasksdays', models.IntegerField(default=0)),
                ('billabledmtproject0002createideasforclientdays', models.IntegerField(default=0)),
                ('billabledmtproject0003inputprepbillableinputprepdays', models.IntegerField(default=0)),
                ('billabledmtproject00031qawiththeclientdays', models.IntegerField(default=0)),
                ('billabledmtproject1streviewdays', models.IntegerField(default=0)),
                ('billabledmtprojectclrrvwptsdays', models.IntegerField(default=0)),
                ('billabledmtproject0004finalreviewdays', models.IntegerField(default=0)),
                ('billabledmtproject0005assemblectcplandays', models.IntegerField(default=0)),
                ('billabledmtproject0006adminwrapupdays', models.IntegerField(default=0)),
                ('enddays', models.IntegerField(default=0)),
                ('startP4', models.IntegerField(default=0)),
                ('billabledmtproject0001setupclienttasksP4', models.IntegerField(default=0)),
                ('billabledmtproject0002createideasforclientP4', models.IntegerField(default=0)),
                ('billabledmtproject0003inputprepbillableinputprepP4', models.IntegerField(default=0)),
                ('billabledmtproject00031qawiththeclientP4', models.IntegerField(default=0)),
                ('billabledmtproject1streviewP4', models.IntegerField(default=0)),
                ('billablectcstcproject0006reviewprojectP4', models.IntegerField(default=0)),
                ('billablectcstcproject0007clrrwptsP4', models.IntegerField(default=0)),
                ('billabledmtprojectclrrvwptsP4', models.IntegerField(default=0)),
                ('billabledmtproject0004finalreviewP4', models.IntegerField(default=0)),
                ('billabledmtproject0005assemblectcplanP4', models.IntegerField(default=0)),
                ('billabledmtproject0006adminwrapupP4', models.IntegerField(default=0)),
                ('billabledmtprojectendP4', models.IntegerField(default=0)),
                ('endP4', models.IntegerField(default=0)),
                ('TotalP4DaysPerStage', models.IntegerField(default=0)),
                ('TotalDaysPerStage', models.IntegerField(default=0)),
                ('TurnAroundTime', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insightly.category')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insightly.pipeline')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insightly.stage')),
                ('user_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insightly.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
