# Generated by Django 3.1.7 on 2021-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectstatuscancelled',
            field=models.BooleanField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectstatuscompleted',
            field=models.BooleanField(default=list, null=True),
        ),
    ]
