# Generated by Django 3.1.7 on 2021-04-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0003_auto_20210414_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline706estate',
            old_name='pipelinesalestaxreturn_id',
            new_name='pipeline706Estate_id',
        ),
    ]
