# Generated by Django 3.1.7 on 2021-04-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0005_auto_20210416_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category706estate',
            old_name='category706Estate_id',
            new_name='category706estate_id',
        ),
        migrations.RenameField(
            model_name='stage706estate',
            old_name='stage706Estate_id',
            new_name='stage706estate_id',
        ),
        migrations.RenameField(
            model_name='usermodel706estate',
            old_name='usermodel706Estate_id',
            new_name='usermodel706estate_id',
        ),
    ]
