# Generated by Django 3.1.7 on 2021-04-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0006_auto_20210416_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline709gift',
            old_name='pipeline709Gift_id',
            new_name='pipeline709gift_id',
        ),
    ]
