# Generated by Django 3.1.7 on 2021-04-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0007_auto_20210416_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage1040x',
            old_name='stage1040X_id',
            new_name='stage1040x_id',
        ),
    ]
