# Generated by Django 3.1.7 on 2021-04-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0008_auto_20210416_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1041estateincome',
            old_name='pipeline1041EstateIncome_id',
            new_name='pipeline1041estateincome_id',
        ),
    ]
