# Generated by Django 3.1.7 on 2021-04-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0009_auto_20210416_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1041trust',
            old_name='pipeline1041Trust_id',
            new_name='pipeline1041trust_id',
        ),
    ]
