# Generated by Django 3.1.7 on 2021-04-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0010_auto_20210416_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1120x',
            old_name='pipeline1120X_id',
            new_name='pipeline1120x_id',
        ),
    ]
