# Generated by Django 3.1.7 on 2021-04-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0012_auto_20210416_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1120s',
            old_name='pipeline1120S_id',
            new_name='pipeline1120s_id',
        ),
        migrations.RenameField(
            model_name='stage1120s',
            old_name='stage1120S_id',
            new_name='stage1120s_id',
        ),
        migrations.RenameField(
            model_name='usermodel1120s',
            old_name='usermodel1120S_id',
            new_name='usermodel1120s_id',
        ),
    ]
