# Generated by Django 3.1.7 on 2021-04-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0013_auto_20210416_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category1120x',
            old_name='categorysalestaxreturn_id',
            new_name='category1120x_id',
        ),
    ]
