# Generated by Django 3.1.7 on 2021-04-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0014_auto_20210416_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category1120s',
            old_name='category1120S_id',
            new_name='category1120s_id',
        ),
    ]
