# Generated by Django 3.1.7 on 2021-04-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0015_auto_20210416_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1065',
            old_name='pipeline1065_id',
            new_name='Pipeline1065_id',
        ),
    ]
