# Generated by Django 3.1.7 on 2021-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0017_auto_20210416_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1120x',
            old_name='project1120X_id',
            new_name='project1120x_id',
        ),
    ]
