# Generated by Django 3.1.7 on 2021-04-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0018_auto_20210416_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline1065x',
            old_name='pipeline1065X_id',
            new_name='pipeline1065x_id',
        ),
    ]
