# Generated by Django 3.1.7 on 2021-04-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0019_auto_20210416_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1120s',
            old_name='project1120S_id',
            new_name='project1120s_id',
        ),
    ]
