# Generated by Django 3.1.7 on 2021-04-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0020_auto_20210417_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage1065x',
            old_name='stage1065X_id',
            new_name='stage1065x_id',
        ),
    ]
