# Generated by Django 3.1.7 on 2021-04-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0022_auto_20210417_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category1065x',
            old_name='category1065X_id',
            new_name='category1065x_id',
        ),
    ]
