# Generated by Django 3.1.7 on 2021-04-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0023_auto_20210417_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category1041estateincome',
            old_name='category1041EstateIncome_id',
            new_name='category1041estateincome_id',
        ),
        migrations.RenameField(
            model_name='project1041estateincome',
            old_name='project1041EstateIncome_id',
            new_name='project1041estateincome_id',
        ),
        migrations.RenameField(
            model_name='stage1041estateincome',
            old_name='stage1041EstateIncome_id',
            new_name='stage1041estateincome_id',
        ),
        migrations.RenameField(
            model_name='usermodel1041estateincome',
            old_name='usermodel1041EstateIncome_id',
            new_name='usermodel1041estateincome_id',
        ),
    ]
