# Generated by Django 3.1.7 on 2021-04-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0025_auto_20210417_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project706estate',
            old_name='project706Estate_id',
            new_name='project706estate_id',
        ),
    ]
