# Generated by Django 3.1.7 on 2021-04-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0026_auto_20210417_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category709gift',
            old_name='category709Gift_id',
            new_name='category709gift_id',
        ),
        migrations.RenameField(
            model_name='project709gift',
            old_name='project709Gift_id',
            new_name='project709gift_id',
        ),
        migrations.RenameField(
            model_name='stage709gift',
            old_name='stage709Gift_id',
            new_name='stage709gift_id',
        ),
        migrations.RenameField(
            model_name='usermodel709gift',
            old_name='usermodel709Gift_id',
            new_name='usermodel709gift_id',
        ),
    ]
