# Generated by Django 3.1.7 on 2021-04-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0027_auto_20210417_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1040x',
            old_name='project1040X_id',
            new_name='project1040x_id',
        ),
    ]
