# Generated by Django 3.1.7 on 2021-04-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0028_auto_20210417_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel1065x',
            old_name='usermodel1065x_id',
            new_name='usermodel1065X_id',
        ),
    ]
