# Generated by Django 3.1.7 on 2021-04-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0030_auto_20210417_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category1120sx',
            old_name='category1120SX_id',
            new_name='category1120sx_id',
        ),
        migrations.RenameField(
            model_name='pipeline1120sx',
            old_name='pipeline1120SX_id',
            new_name='pipeline1120sx_id',
        ),
        migrations.RenameField(
            model_name='project1120sx',
            old_name='project1120SX_id',
            new_name='project1120sx_id',
        ),
        migrations.RenameField(
            model_name='stage1120sx',
            old_name='stage1120SX_id',
            new_name='stage1120sx_id',
        ),
        migrations.RenameField(
            model_name='usermodel1120sx',
            old_name='usermodel1120SX_id',
            new_name='usermodel1120sx_id',
        ),
    ]
