# Generated by Django 3.1.7 on 2021-04-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightly', '0031_auto_20210417_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1040x',
            old_name='eeAnalysis1040X0016',
            new_name='FeeAnalysis1040X0016',
        ),
        migrations.RenameField(
            model_name='project1040x',
            old_name='eeAnalysis1040X0016P4',
            new_name='FeeAnalysis1040X0016P4',
        ),
    ]
